let task_completed = [
    {
        "WORK": "НАС657",
        "CLIENT": "Ремарк",
        "PRODUCT": "Худи унисекс STAN футер",
        "COLOR": "red",
        "ARTICLE": "СТ44667",
        "QUANTITY": "15",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": " ",
        "STATUS": 0,
    },
    {
        "WORK": "НАС657",
        "CLIENT": "Ремарк",
        "PRODUCT": "Худи унисекс STAN футер",
        "COLOR": "#001E36",
        "ARTICLE": "СТ45127",
        "QUANTITY": "15",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": " ",
        "STATUS": 0,
    },

    {
        "WORK": " ",
        "CLIENT": "Гафиятуллина Э. Я.",
        "PRODUCT": "Сумка для обуви",
        "COLOR": "gray",
        "ARTICLE": " ",
        "QUANTITY": "1",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": " ",
    },

    {
        "WORK": " ",
        "CLIENT": "Гафиятуллина Э. Я.",
        "PRODUCT": "Сумка для обуви",
        "COLOR": "blue",
        "ARTICLE": " ",
        "QUANTITY": "1",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": "",
    },
]