let task_DP = [
    {
        "WORK":     "",
        "CLIENT":   "ТЕКО",
        "PRODUCT":  "Блокнот",
        "MATERIAL": "M270",
        "ARTICLE":  "ТАТСКА4799.0001",
        "QUANTITY": "100",
        "TERM":     "14.02.25",
        "NOTE":     "Переднюю и заднюю обложку",
        "STATUS":   0,
    },
    {
        "WORK":     "",
        "CLIENT":   "Rocada Med",
        "PRODUCT":  "",
        "MATERIAL": "M270",
        "ARTICLE":  "-",
        "QUANTITY": "~500",
        "TERM":     "-",
        "NOTE":     "нет визуализации",
        "STATUS":   1,
    },
//    {
//        "WORK":     "",
//        "CLIENT":   "",
//        "PRODUCT":  "",
//        "MATERIAL": "",
//        "ARTICLE":  "",
//        "QUANTITY": "",
//        "TERM":     "",
//        "NOTE":     "",
//        "STATUS":   2,
//    },
]