let task_DP = [
//    {
//        "WORK": "ДН2185",
//        "CLIENT": "Дуслык",
//        "PRODUCT": "наклейки D=25mm",
//        "MATERIAL": "glue",
//        "ARTICLE": "РЕ5000",
//        "QUANTITY": "200",
//        "TERM": "04.02.25",
//        "NOTE": "🖨️ ✂️ отдать Наташе",
//        "STATUS": 1,
//    },
    
//    {
//        "WORK":     "РС5592",
//        "CLIENT":   "Финист",
//        "PRODUCT":  "Шубер",
//        "MATERIAL": "РС5592.0001",
//        "ARTICLE":  "",
//        "QUANTITY": "",
//        "TERM":     "",
//        "NOTE":     "",
//        "STATUS":   2,
//    },
//    {
//        "WORK":     "",
//        "CLIENT":   "",
//        "PRODUCT":  "",
//        "MATERIAL": "",
//        "ARTICLE":  "",
//        "QUANTITY": "",
//        "TERM":     "",
//        "NOTE":     "",
//        "STATUS":   0,
//    },
//
//    {
//        "WORK":     "ВП2327",
//        "CLIENT":   "АгроБиоПром",
//        "PRODUCT":  "",
//        "MATERIAL": "310x930 300",
//        "ARTICLE":  "РЕ ВП2327.0005",
//        "QUANTITY": "50",
//        "TERM":     "10.02.25 9:00",
//        "NOTE":     "",
//        "STATUS":   0,
//    },
//
//    {
//        "WORK":     "",
//        "CLIENT":   "1С-Рарус",
//        "PRODUCT":  "",
//        "MATERIAL": "M 150",
//        "ARTICLE":  "ШР3406",
//        "QUANTITY": "300",
//        "TERM":     "11.02.25 15:00",
//        "NOTE":     "",
//        "STATUS":   2,
//    },
//
//    {
//        "WORK":     "",
//        "CLIENT":   "IronMaster",
//        "PRODUCT":  "",
//        "MATERIAL": "glue paper",
//        "ARTICLE":  "РЕКЛ4955.0003",
//        "QUANTITY": "1260",
//        "TERM":     "11.02.25 15:00",
//        "NOTE":     "",
//        "STATUS":   2,
//    },
    
//    {
//        "WORK":     "",
//        "CLIENT":   "ПЭМЗ Молот",
//        "PRODUCT":  "",
//        "MATERIAL": "M270",
//        "ARTICLE":  "РЕВП2358.0001",
//        "QUANTITY": "30",
//        "TERM":     "12.02.25 15:00",
//        "NOTE":     "",
//        "STATUS":   0,
//    },
    {
        "WORK":     "НАС707",
        "CLIENT":   "Ремарк",
        "PRODUCT":  "открытка",
        "MATERIAL": "M270",
        "ARTICLE":  "реинд",
        "QUANTITY": "8",
        "TERM":     "13.02.25",
        "NOTE":     "",
        "STATUS":   0,
    },

    {
        "WORK":     "НАС707",
        "CLIENT":   "Ремарк",
        "PRODUCT":  "открытка",
        "MATERIAL": "M270",
        "ARTICLE":  "реинд",
        "QUANTITY": "12",
        "TERM":     "13.02.25",
        "NOTE":     "",
        "STATUS":   0,
    },

    {
        "WORK":     "ДХ6685",
        "CLIENT":   "ТракРесурс Регион",
        "PRODUCT":  "Ароматический набор",
        "MATERIAL": "M270",
        "ARTICLE":  "ОА445004",
        "QUANTITY": "10",
        "TERM":     "14.02.25",
        "NOTE":     "",
        "STATUS":   2,
    },

    {
        "WORK":     "",
        "CLIENT":   "Rocada Med",
        "PRODUCT":  "",
        "MATERIAL": "M270",
        "ARTICLE":  "-",
        "QUANTITY": "~500",
        "TERM":     "-",
        "NOTE":     "нет визуализации",
        "STATUS":   1,
    },
]