let task_DTF = [
    {
        "WORK":         "",
        "CLIENT":       "Глобус",
        "PRODUCT":      "Мешок с головоломкой",
        "COLOR":        "gray",
        "ARTICLE":      "ОА19544809",
        "QUANTITY":     "30",
        "TERM":         "10.02.25 9:00",
        "NOTE":         "",
        "STATUS": 0,
    },

    {
        "WORK":         "",
        "CLIENT":       "Щёкиназот",
        "PRODUCT":      "Лейбл",
        "COLOR":        "#343434",
        "ARTICLE":      "ПР13943,13",
        "QUANTITY":     "20",
        "TERM":         "11.02.25 9:00",
        "NOTE":         "",
        "STATUS": 2,
    },

    {
        "WORK":         "",
        "CLIENT":       "Логикам",
        "PRODUCT":      "Нессер",
        "COLOR":        "darkred",
        "ARTICLE":      "ПР13922,55",
        "QUANTITY":     "75",
        "TERM":         "11.02.25 9:00",
        "NOTE":         "",
        "STATUS": 2,
    },

    {
        "WORK":         "",
        "CLIENT":       "Логикам",
        "PRODUCT":      "Рюкзак",
        "COLOR":        "blue",
        "ARTICLE":      "АР4006,22",
        "QUANTITY":     "51",
        "TERM":         "11.02.25 9:00",
        "NOTE":         "",
        "STATUS": 2,
    },

//    {
//        "WORK":         "",
//        "CLIENT":       "",
//        "PRODUCT":      "",
//        "COLOR":        "",
//        "ARTICLE":      "",
//        "QUANTITY":     "",
//        "TERM":         "",
//        "NOTE":         "",
//        "STATUS": 0,
//    },
//    {
//        "WORK": "СКА4759",
//        "CLIENT": "Bala City",
//        "PRODUCT": "Шоппер",
//        "COLOR": "gray",
//        "ARTICLE": "ПР11293,11",
//        "QUANTITY": "150",
//        "DEPARTMENT": "DTF",
//        "TERM": "04.02.25",
//        "NOTE": "Макет был изменён: убраны мелкие элементы (мелкие острова)",
//        "STATUS": 0,
//    },

//    {
//        "WORK": "РС5623",
//        "CLIENT": "Оргсинтез",
//        "PRODUCT": "Сумка светоотражающая",
//        "COLOR": "gray",
//        "ARTICLE": "ОА887157",
//        "QUANTITY": "8",
//        "DEPARTMENT": "DTF",
//        "TERM": "04.02.25",
//        "NOTE": "",
//        "STATUS": null,
//    },
    
//    {
//        "WORK": "РС5623",
//        "CLIENT": "Оргсинтез",
//        "PRODUCT": "Сумка светоотражающая",
//        "COLOR": "#CDE092",
//        "ARTICLE": "ПР16497,9",
//        "QUANTITY": "8",
//        "DEPARTMENT": "DTF",
//        "TERM": "06.02.25",
//        "NOTE": "",
//        "STATUS": null,
//    },

//    {
//        "WORK": "№ 123",
//        "CLIENT": "Клиент",
//        "PRODUCT": "Продукт и его цвет:",
//        "COLOR": "orange",
//        "ARTICLE": "ПР12345",
//        "QUANTITY": "10",
//        "DEPARTMENT": "DTF",
//        "TERM": "01.01.25",
//        "NOTE": "Комментарий к заказу",
//        "STATUS": 1,
//    },
]
