let task = [
    {
        "WORK": "НАС657",
        "CLIENT": "Ремарк",
        "PRODUCT": "Худи унисекс STAN футер",
        "COLOR": "red",
        "ARTICLE": "СТ44667",
        "QUANTITY": "15",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": " ",
        "STATUS": 0,
    },
    {
        "WORK": "НАС657",
        "CLIENT": "Ремарк",
        "PRODUCT": "Худи унисекс STAN футер",
        "COLOR": "#001E36",
        "ARTICLE": "СТ45127",
        "QUANTITY": "15",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": " ",
        "STATUS": 0,
    },

    {
        "WORK": "НЭД4252",
        "CLIENT": "Теребро",
        "PRODUCT": "Бейсболка Standart",
        "COLOR": "black",
        "ARTICLE": "ПР15847,3",
        "QUANTITY": "50",
        "DEPARTMENT": "DTF",
        "TERM": "28.01.25",
        "NOTE": " ",
    },

    {
        "WORK": "НЭД4252",
        "CLIENT": "Теребро",
        "PRODUCT": "Футболка мужская IMPERIAL",
        "COLOR": "black",
        "ARTICLE": "ХЭ711500.309/L",
        "QUANTITY": "50",
        "DEPARTMENT": "DTF",
        "TERM": "28.01.25",
        "NOTE": " ",
    },

    {
        "WORK": " ",
        "CLIENT": "Гафиятуллина Э. Я.",
        "PRODUCT": "Сумка для обуви",
        "COLOR": "gray",
        "ARTICLE": " ",
        "QUANTITY": "1",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": " ",
    },

    {
        "WORK": " ",
        "CLIENT": "Гафиятуллина Э. Я.",
        "PRODUCT": "Сумка для обуви",
        "COLOR": "blue",
        "ARTICLE": " ",
        "QUANTITY": "1",
        "DEPARTMENT": "DTF",
        "TERM": "27.01.25",
        "NOTE": "",
    },

    {
        "WORK": "№ 123",
        "CLIENT": "Клиент",
        "PRODUCT": "Продукт и его цвет:",
        "COLOR": "orange",
        "ARTICLE": "ПР12345",
        "QUANTITY": "10",
        "DEPARTMENT": "DTF",
        "TERM": "01.01.25",
        "NOTE": "Комментарий к заказу",
        "STATUS": 1,
    },


]
